---
apiVersion: v1
kind: Service
metadata:
  name: my-ruby-app-svc
spec:
  selector:  # Метки, используемые для определения подов, которые будут обслуживаться этим сервисом.
    app: demo-ruby-app  # Метка приложения, которое будет обслуживаться.
  type: ClusterIP
  ports:
    - name: http
      port: 3000 # Порт, по которому сервис будет доступен внутри кластера.
      targetPort: 3000 # Порт внутри контейнера
      protocol: TCP # Протокол, используемый для связи.
